version: '3'

services:
  cot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HOST=0.0.0.0
      - VIRTUAL_HOST=o1-preview-sonnet-llama.multiplewords.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=o1-preview-sonnet-llama.multiplewords.com
      - LETSENCRYPT_EMAIL=multiple.words.one@gmail.com
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy

